language: node_js
node_js: 8
cache:
  yarn: true
  directories:
  - node_modules
  - "${NVM_PATH}_modules"
install:
- yarn
- cd functions && yarn && cd ..
script:
- yarn lint
- echo "Building..."
- if [ "$TRAVIS_BRANCH" == "develop" ]; then yarn build; fi
- if [ "$TRAVIS_BRANCH" == "master" ]; then yarn build:prod; fi
before_deploy:
- echo "Deploying!"
deploy:
- provider: firebase
  skip_cleanup: true
  on:
    branch: master
  project: android-makers-2019
  token:
    secure: OagUKutTSaIrj81i0CYR0egkp5wx6KLR3GxshrEVUMlmDXhKnNkhbpES4LBm67OJvdd9MhWEwO1USrHM9dWm9EHeqMhBNRY/zctOjKPzZmIdMhThiI8JDBaLlQR/CA2LDqVVsYjuNoqKeL2/zoXi8XEnmStLLBtwzXyVzLbAb/TDk5Yy3lh9vZLWoCe7khOqCeS/mJgKKQtaemOGqAqx9ji3Q0QHe4e2qG6HMfTg8c66ktqF/wHloWKl/jlAY6krW3UKshFAauRyl4+NNt+Q0hLPo/uDyVCGQfUW3woYKGUjEjML+roO8Xrm8ONhMTDTHCwT+CBKxR3Hx5ahzb2f+glYx0BfB/bMEGlxNSK3uRg8kfOkGt+k+ViGpIMv20/Njh2PP6EhuAfFgOb8j8E7ce0J3LX4Fs2VLSAJukG6cXijGYBEdfFiNBhw8z32czT4npyje6MhaLq0mlPlNovx05a/Kis9QL41q7SlpjncmEsgqAK0WLLU4PMOeXjWHXKzeeruryfnR3DRpCVRehb8J782mx2U4MoAId5pS8xyEnaFCZdriH3SLn73TK/4JPBGyOygaTzTFkO98BtwkVNHiZ/af2oMY1W19m3QhTAc7c4jgNrj8D7IinA+iydLdkxi4vxkdyl3pzCRqA5WIXVPs+ykIk+5rGq6Bv7+zISiXKo=
- provider: firebase
  skip_cleanup: true
  on:
    branch: develop
  project: android-makers-2019
  token:
    secure: OagUKutTSaIrj81i0CYR0egkp5wx6KLR3GxshrEVUMlmDXhKnNkhbpES4LBm67OJvdd9MhWEwO1USrHM9dWm9EHeqMhBNRY/zctOjKPzZmIdMhThiI8JDBaLlQR/CA2LDqVVsYjuNoqKeL2/zoXi8XEnmStLLBtwzXyVzLbAb/TDk5Yy3lh9vZLWoCe7khOqCeS/mJgKKQtaemOGqAqx9ji3Q0QHe4e2qG6HMfTg8c66ktqF/wHloWKl/jlAY6krW3UKshFAauRyl4+NNt+Q0hLPo/uDyVCGQfUW3woYKGUjEjML+roO8Xrm8ONhMTDTHCwT+CBKxR3Hx5ahzb2f+glYx0BfB/bMEGlxNSK3uRg8kfOkGt+k+ViGpIMv20/Njh2PP6EhuAfFgOb8j8E7ce0J3LX4Fs2VLSAJukG6cXijGYBEdfFiNBhw8z32czT4npyje6MhaLq0mlPlNovx05a/Kis9QL41q7SlpjncmEsgqAK0WLLU4PMOeXjWHXKzeeruryfnR3DRpCVRehb8J782mx2U4MoAId5pS8xyEnaFCZdriH3SLn73TK/4JPBGyOygaTzTFkO98BtwkVNHiZ/af2oMY1W19m3QhTAc7c4jgNrj8D7IinA+iydLdkxi4vxkdyl3pzCRqA5WIXVPs+ykIk+5rGq6Bv7+zISiXKo=
